# This is a basic workflow to help you get started with Actions

name: Deploy main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.23.x

      # - name: Ensure dependencies are up to date
      #   run: |
      #     make ensure

      - name: Run Gosec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -exclude=G404 ./...

      - name: Run Trivy vulnerability scanner in FS mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          security-checks: 'vuln,config'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Build the image
        run: |
          docker build -t ottosulin/simplegoservice:${{ github.sha }} .
          docker build -t ottosulin/simplegoservice:latest .

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1
          
      - name: Sign the images with cosign
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign ottosulin/simplegoservice:${{ github.sha }}
          cosign sign ottosulin/simplegoservice:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to registry
        run: |
          docker push ottosulin/simplegoservice:${{ github.sha }}
          docker push ottosulin/simplegoservice:latest
      

#### Old stuff ####

      # - name: Verify that repo SBOM and DockerHub container are the same
      #   run: |
      #     curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.28.1
      #     docker build -t ottosulin/simplegoservice:latest .
      #     trivy image --format cyclonedx --output sbom_candidate.json ottosulin/simplegoservice:latest
      #     diff sbom.json sbom_candidate.json

      # - name: Verify SBOM signature
      #   run: |
      #     cosign verify-blob --key cosign/cosign.pub --signature $(cat sbom.sig) sbom.json

      # - name: Scan the built container image
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'ottosk8slab.azurecr.io/simplegoservice:${{ github.sha }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'

