# This is a basic workflow to help you get started with Actions

name: Deploy main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      # TODO: enable after publishing project
      # - name: OSSF Scorecard
      #   env:
      #     PAT: ${{ secrets.GDPAT }}
      #   run: |
      #     docker run -e GITHUB_AUTH_TOKEN=${{ secrets.GDPAT }} gcr.io/openssf/scorecard:stable --show-details --repo=https://github.com/ottosulin/aws-gd-threatintel

      # TODO: official actions fails to find packages for some strange reason
      - name: Run Gosec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -exclude=G404 ./...

      - name: Build the image
        run: |
          docker build -t ottosk8slab.azurecr.io/simplegoservice:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ottosk8slab.azurecr.io/simplegoservice:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ottosk8slab.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Push to registry
        run: |
          docker push ottosk8slab.azurecr.io/simplegoservice:${{ github.sha }}
          docker push ottosk8slab.azurecr.io/simplegoservice:latest
